---
name: reviewdog

on:
  pull_request:
    branches:
    - master

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: detect-secrets
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        workdir: testdata
